set nocompatible
filetype indent plugin on
syntax on

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'nvie/vim-flake8'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-easytags'
Plugin 'majutsushi/tagbar'
call vundle#end()

set hidden
set wildmenu
set showcmd
set hlsearch
set incsearch

set ignorecase
set smartcase

set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler

set laststatus=2
set confirm
set visualbell
set t_vb=
set mouse=a
set cmdheight=2
set number
set notimeout ttimeout ttimeoutlen=200

set shiftwidth=4
set softtabstop=4
set expandtab

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=10      "deepest fold is 10 levels
set nofoldenable        "dont fold by default
set foldlevel=1         "this is just what i use

map Y y$
nnoremap <C-L> :nohl<CR><C-L>

set viminfo='10,\"100,:20,%,n~/.viminfo

if has("autocmd")
      au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

command WQ wq
command Wq wq
command W w
command Q q

" f7 to run
let g:flake8_max_line_length=150

nmap <F8> :TagbarToggle<CR>

colorscheme distinguished
