---
- hosts: localhost
  vars:
      packages: [ '@Development tools', 'epel-release.noarch', 'vim', 'git', 'zsh', 'nmap', 'dstat', 'sysstat', 'htop', 'bind-utils', 'wget' ]
  tasks:
     - name: Install Packages
       package: name={{ packages }} state=present
       when: ansible_os_family == "RedHat"
       become: true

     - name: Yum System Update
       cron:
         name: Yum System Update
         weekday: 4
         minute: 0
         hour: 13
         user: root
         job: "/bin/yum update -y"
       when: ansible_os_family == "RedHat"
       become: true
