---
- hosts: localhost
  vars:
      yum_packages: [ '@Development tools', 'vim', 'git', 'zsh', 'nmap', 'dstat', 'sysstat', 'python3', 'bind-utils', 'wget' ]
  tasks:
     - name: Install Yum Packages
       package: name={{ yum_packages }} state=present
       with_items: "{{ yum_packages }}"
       when: ansible_os_family == "RedHat"
       become: true

     - name: Yum System Update
       cron:
         name: Yum System Update
         weekday: 4
         minute: 0
         hour: 13
         user: root
         job: "/bin/yum update -y"
       when: ansible_os_family == "RedHat"
       become: true
