#autoload -U compinit promptinit
#compinit
#promptinit

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

prompt skwp

# Aliases
alias ll="ls -l"
alias sl=sl
alias grep=grep

export PATH=$PATH:$HOME/bin:/usr/local/bin
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# 256 colored tmux
alias tmux="tmux -2"
export TERM=xterm-256color

alias ls="ls -F"

# Vim as default editor
export EDITOR=vim

git config --global core.editor vim

# Python virtual environment
if [ -r /usr/local/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    source /usr/local/bin/virtualenvwrapper.sh
fi

envfile="$HOME/.gnupg/gpg-agent.env"
if [ -e "$envfile" ] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
    eval "$(cat "$envfile")"
else
    eval "$(gpg-agent --daemon --write-env-file "$envfile")"
fi
export GPG_AGENT_INFO  # the env file does not contain the export statement

if [ $(uname -s) = "OpenBSD" ]; then
    alias pkg_search="pkg_info -Q"
    #export PKG_PATH=ftp://ftp.openbsd.org/pub/OpenBSD/5.6/packages/amd64/
    PKG_PATH=http://mirrors.rit.edu/OpenBSD/$(uname -r)/packages/$(arch -s)/
    export PKG_PATH=https://stable.mtier.org/updates/$(uname -r)/$(arch -s):${PKG_PATH}
fi
