# load zgen
source $HOME/dotfiles/zgen/zgen.zsh

DISABLE_UPDATE_PROMPT=true

# check if there's no init script
if ! zgen saved; then
    echo Creating a zgen save

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/pass
    zgen oh-my-zsh plugins/virtualenvwrapper

    # completions
    zgen load zsh-users/zsh-completions src

    # theme
    zgen oh-my-zsh themes/gentoo

    # save all to init script
    zgen save
fi

export PATH=$HOME/bin:/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# 256 colored tmux
alias tmux="tmux -2"
export TERM=xterm-256color

# Vim as default editor
export EDITOR=vim

# TRAINS
alias sl=sl
alias grep=grep

# Python virtual environment
#if [ -r /usr/local/bin/virtualenvwrapper.sh ]; then
#    export WORKON_HOME=$HOME/.virtualenvs
#    source /usr/local/bin/virtualenvwrapper.sh
#fi

#envfile="$HOME/.gnupg/gpg-agent.env"
#if [ -e "$envfile" ] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
#    eval "$(cat "$envfile")"
#else
#    eval "$(gpg-agent --daemon --write-env-file "$envfile")"
#fi
#export GPG_AGENT_INFO  # the env file does not contain the export statement
#export SSH_AUTH_SOCK   # enable gpg-agent for ssh

if [ $(uname -s) = "OpenBSD" ]; then
    alias pkg_search="pkg_info -Q"
    #export PKG_PATH=ftp://ftp.openbsd.org/pub/OpenBSD/5.6/packages/amd64/
    export PKG_PATH=http://mirrors.rit.edu/OpenBSD/5.7/packages/amd64/
fi
